apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-website-deployment
  labels:
    app: nginx-website
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-website
  template:
    metadata:
      labels:
        app: nginx-website
    spec:
      containers:
        - name: nginx-website
          image: paciluciano/nginx-website:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
